image: 
- Ubuntu
- Visual Studio 2017

platform: x64

configuration:
  - Release
  - Debug

install:
  - cmd: set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - cmd: set PATH=%APPVEYOR_BUILD_FOLDER%\..\depot_tools;%PATH%
  - sh: export PATH=${APPVEYOR_BUILD_FOLDER}/../depot_tools:${PATH}
  - cmd: set GENERATOR="Visual Studio 15 2017 Win64"
  - sh: export GENERATOR="Unix Makefiles"
  - cmd: set
  - sh: env
  - git submodule update --init
  - cd ..
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
  - mkdir webrtc
  - cd webrtc
  - fetch --no-history --nohooks webrtc 
  - cd src
  - ps: echo CONFIGURATION=$env:CONFIGURATION PLATFORM=$env:PLATFORM GENERATOR=$env:GENERATOR
  - ps: (get-content DEPS) | foreach-object {$_ -replace "'src/resources'],", "'src/resources'],'condition':'rtc_include_tests==true',"} | set-content DEPS
  - gclient sync
  - sh: sudo apt-get update && sudo apt-get install -y --no-install-recommends autoconf automake libtool xz-utils libgtk-3-dev libasound2-dev

before_build:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - cmd: cmake -G %GENERATOR% -D WEBRTCBUILD=%CONFIGURATION% .
  - sh: cmake -G "${GENERATOR}" -D WEBRTCBUILD=${CONFIGURATION} .

build_script:
  - cmd: msbuild INSTALL.vcxproj /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - sh: make

after_build:
  - ps: cpack -C "$env:CONFIGURATION"

artifacts:
  - path: webrtc-streamer*.tar.gz

deploy:
  provider: GitHub
  auth_token:
    secure: Ov3sAkiU1iRjAOc7GYaScSUujzhKiTCz/gZ4uQws2fTaNu8O5FUciAQk4uuGeiC7
  draft: false
  prerelease: false
  on:
    branch: master                 
    appveyor_repo_tag: true       

