name: Update Codeberg mirror

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://codeberg.org/${{ github.repository }}.git'
        GIT_USERNAME: ${{ github.actor }}
        GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}

    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://gitlab.com/${{ github.repository }}.git'
        GIT_USERNAME: ${{ github.actor }}
        GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}